# Generated by Django 5.1.9 on 2025-06-01 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Referencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True)),
                ("autores", models.CharField(blank=True, max_length=255)),
                ("ano", models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name="term",
            old_name="author",
            new_name="autor",
        ),
        migrations.RenameField(
            model_name="term",
            old_name="created_date",
            new_name="data_criacao",
        ),
        migrations.RenameField(
            model_name="term",
            old_name="related_terms",
            new_name="termos_relacionados",
        ),
        migrations.RenameField(
            model_name="term",
            old_name="name",
            new_name="titulo",
        ),
        migrations.RemoveField(
            model_name="term",
            name="definition",
        ),
        migrations.RemoveField(
            model_name="term",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="term",
            name="published_date",
        ),
        migrations.CreateModel(
            name="Definicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("image_url", models.URLField(blank=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "termo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="definicoes",
                        to="core.term",
                    ),
                ),
                (
                    "referencias",
                    models.ManyToManyField(blank=True, to="core.referencia"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exemplo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                (
                    "definicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exemplos",
                        to="core.definicao",
                    ),
                ),
            ],
        ),
    ]
