# Generated by Django 5.1.9 on 2025-06-01 23:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_referencia_rename_author_term_autor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Term",
            new_name="Termo",
        ),
    ]
