# Generated by Django 5.1.9 on 2025-06-01 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_term_termo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Capitulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="termo",
            name="capitulo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="termos",
                to="core.capitulo",
            ),
        ),
    ]
