# Generated by Django 5.1.9 on 2025-06-01 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_capitulo_termo_capitulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termo",
            name="capitulo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="termos",
                to="core.capitulo",
            ),
        ),
    ]
